import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
//import "bootstrap/dist/css/bootstrap.min.css";
import Providers from "./providers";
import CartDrawerContainer from "@/components/modalCart/CartDrawerContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
(function() {
  try {
    var stored = localStorage.getItem('theme'); // 'light' | 'dark' | null (sistema)
    var root = document.documentElement;

    // Limpia primero
    root.removeAttribute('data-theme');

    if (stored === 'dark') {
      root.setAttribute('data-theme', 'dark');
    } else if (stored === 'light') {
      // Forzamos claro: usamos data-theme="light" para bloquear el fallback oscuro del sistema.
      root.setAttribute('data-theme', 'light');
    } // else: sin atributo => aplica tu fallback @media (sistema)

    // Ajusta color-scheme para formularios/scrollbars
    var meta = document.querySelector('meta[name="color-scheme"]');
    if (!meta) {
      meta = document.createElement('meta');
      meta.setAttribute('name', 'color-scheme');
      document.head.appendChild(meta);
    }
    var isDark = root.getAttribute('data-theme') === 'dark' ||
                 (!root.hasAttribute('data-theme') && window.matchMedia('(prefers-color-scheme: dark)').matches);
    meta.setAttribute('content', isDark ? 'dark light' : 'light dark');
  } catch (_) {}
})();
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Evita parpadeo y respeta preferencia antes del primer render */}
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <meta name="color-scheme" content="light dark" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {children}

          <CartDrawerContainer />
        </Providers>
      </body>
    </html>
  );
}
